### ISSUE TITLE
Server always crashes when banana suckling tries to grow to the next phase

### ISSUE THREAD

**Issue by tomssuli** [DynamicTreesTeam/DynamicTrees-Neapolitan#1]
Issue is reproduced when I plant a banana suckling to any ground and wait for a while. Supposedly crash is triggered when it tries to grow to the second phase. When I restart server, the planted suckling is still on the first phase and if I wait for a while, the server crashes again. This goes on until I remove the banana plants from the ground.

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 20.1.2022 11:27
Description: Exception ticking world

java.lang.NoSuchMethodError: com.ferreusveritas.dynamictrees.blocks.rootyblocks.SoilHelper.isSoilAcceptable(Lnet/minecraft/block/Block;I)Z
	at maxhyper.dtneapolitan.trees.BananaSpecies.canSaplingGrowNaturally(BananaSpecies.java:34) ~[dtneapolitan:1.16.5-1.0.1] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.DynamicSaplingBlock.func_225534_a_(DynamicSaplingBlock.java:79) ~[dynamictrees:1.16.5-0.10.0-Beta26] {re:classloading}
	at net.minecraft.block.AbstractBlock.func_225542_b_(AbstractBlock.java:287) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:367) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_311] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at maxhyper.dtneapolitan.trees.BananaSpecies.canSaplingGrowNaturally(BananaSpecies.java:34) ~[dtneapolitan:1.16.5-1.0.1] {re:classloading}
	at com.ferreusveritas.dynamictrees.blocks.DynamicSaplingBlock.func_225534_a_(DynamicSaplingBlock.java:79) ~[dynamictrees:1.16.5-0.10.0-Beta26] {re:classloading}
	at net.minecraft.block.AbstractBlock.func_225542_b_(AbstractBlock.java:287) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:367) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_311] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Tomssuli'/127, l='ServerLevel[MansikkaHillo]', x=1748.07, y=78.00, z=-2591.46]]
	Chunk stats: ServerChunkCache: 3706
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,63,102), Chunk: (at 0,3,6 in 4,6; contains blocks 64,0,96 to 79,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18101368 game time, 3475925 day time
	Level name: MansikkaHillo
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 5764 (now: true), thunder time: 5764 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7306229040 bytes (6967 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 13 total; -Xms8G -Xmx8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.23.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.23
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		scorge@3.1.3
	Mod List: 
		forge-1.16.5-36.2.23-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.4        |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.4.7+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.4.7+1.16.5        |DONE      |Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.1.jar                   |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.136.jar                          |Just Enough Items             |jei                           |7.7.1.136           |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		Abundance-1.16.5-1.0.5.jar                        |Abundance                     |abundance                     |1.16.5-1.0.5        |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.16.5-3.0.3.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.3               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.16.5-4.1.2.jar                       |Berry Good                    |berry_good                    |4.1.2               |DONE      |Manifest: NOSIGNATURE
		personality-1.16.5-1.0.3.jar                      |Personality                   |personality                   |1.0.3               |DONE      |Manifest: NOSIGNATURE
		atmospheric-1.16.5-3.1.1.jar                      |Atmospheric                   |atmospheric                   |3.1.1               |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.2.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.2               |DONE      |Manifest: NOSIGNATURE
		extraboats-1.16.5-2.1.1.jar                       |Extra Boats                   |extraboats                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.2.0.jar                  |Savage & Ravage               |savageandravage               |3.2.0               |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.23.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.23.0             |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.2.jar                        |Autumnity                     |autumnity                     |2.1.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.16.5-1.2.1.jar                |Abnormals Delight             |abnormals_delight             |1.2.1               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.1.jar                    |Environmental                 |environmental                 |1.1.1               |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1 (1).jar            |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		bamboo_blocks-1.16.5-3.0.1.jar                    |Bamboo Blocks                 |bamboo_blocks                 |3.0.1               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		allurement-1.16.5-1.2.1.jar                       |Allurement                    |allurement                    |1.2.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.23-universal.jar                |Forge                         |forge                         |36.2.23             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-321.jar                                |Quark                         |quark                         |r2.4-321            |DONE      |Manifest: NOSIGNATURE
		Bibliotheca-1.16.5-1.6.2.jar                      |Bibliotheca                   |bibliotheca                   |1.6.2               |DONE      |Manifest: NOSIGNATURE
		ITank-1.16.5-1.7.0.jar                            |ITank                         |itank                         |1.7.0               |DONE      |Manifest: NOSIGNATURE
		stackrefill_1.16.5-1.8.jar                        |Stack Refill                  |stackrefill                   |1.8                 |DONE      |Manifest: NOSIGNATURE
		moveplus-1.16.4-2.5.1.jar                         |Move Plus                     |moveplus                      |1.16.4-2.5.1        |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.5.438-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.5.438           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CBMultipart-1.16.5-3.0.3.122-universal.jar        |CBMultipart                   |cb_multipart                  |3.0.3.122           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		ProjectRed-1.16.5-4.11.0-beta-6-core.jar          |ProjectRed Core               |projectred-core               |4.11.0-beta-6       |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.11.0-beta-6-transmission.jar  |ProjectRed Transmission       |projectred-transmission       |4.11.0-beta-6       |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.11.0-beta-6-exploration.jar   |ProjectRed Exploration        |projectred-exploration        |4.11.0-beta-6       |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.11.0-beta-6-integration.jar   |ProjectRed Integration        |projectred-integration        |4.11.0-beta-6       |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.11.0-beta-6-illumination.jar  |ProjectRed Illumination       |projectred-illumination       |4.11.0-beta-6       |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta26.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta26|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar          |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta10 |DONE      |Manifest: NOSIGNATURE
		DynamicTreesQuark-1.16.5-2.1.1.jar                |Dynamic Trees for Quark       |dtquark                       |1.16.5-2.1.1        |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.16.5-2.2.1.jar                       |Neapolitan                    |neapolitan                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		DynamicTreesNeapolitan-1.16.5-1.0.1.jar           |Dynamic Trees for Neapolitan  |dtneapolitan                  |1.16.5-1.0.1        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: edf8598f-69a3-4c44-b87c-f366d69e869e
	Player Count: 1 / 20; [ServerPlayerEntity['Tomssuli'/127, l='ServerLevel[MansikkaHillo]', x=1748.07, y=78.00, z=-2591.46]]
	Data Packs: vanilla, mod:farmersdelight, mod:repurposed_structures, mod:betterdungeons, mod:jei, mod:abnormals_core, mod:abundance, mod:buzzier_bees, mod:berry_good, mod:personality, mod:atmospheric, mod:upgrade_aquatic, mod:extraboats, mod:savageandravage, mod:bettercaves (incompatible), mod:xaerominimap, mod:autumnity, mod:autoreglib (incompatible), mod:abnormals_delight, mod:yungsextras, mod:yungsapi, mod:environmental, mod:betterstrongholds, mod:bamboo_blocks, mod:allurement, mod:forge, mod:quark (incompatible), mod:bibliotheca, mod:itank (incompatible), mod:codechickenlib (incompatible), mod:cb_multipart (incompatible), mod:projectred-core (incompatible), mod:projectred-transmission (incompatible), mod:projectred-exploration (incompatible), mod:projectred-integration (incompatible), mod:projectred-illumination (incompatible), mod:twilightforest, mod:dynamictrees, mod:dynamictreesplus, mod:dtquark, mod:bettermineshafts, mod:neapolitan, mod:dtneapolitan, mod:collective, mod:stackrefill, mod:moveplus (incompatible), mod:endergetic
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by supermassimo** [comment]
You are using outdated versions of both Dynamic Trees and Dynamic Trees for Neapolitan
